default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: barrails_db
  username: postgres
  password: password
  host: localhost
  port: 5433
  #port: 5432

test:
  <<: *default
  database: barrails_db_test
  username: postgres
  password: password
  host: localhost
  port: 5433
  #port: 5432

production:
  primary: &primary_database_connection # <--- THIS LINE IS CRUCIAL FOR THE ANCHOR
    <<: *default # Inherit adapter, encoding, pool, timeout from default
    url: <%= ENV['DATABASE_URL'] %> # Heroku's database URL

  queue:
    <<: *primary_database_connection

  cache:
    <<: *primary_database_connection