default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: barrails_db # <--- REPLACE WITH YOUR LOCAL DEVELOPMENT DATABASE NAME
  username: postgres
  password: password # <--- REPLACE WITH YOUR LOCAL POSTGRES PASSWORD
  host: localhost
  port: 5432

test:
  <<: *default
  database: barrails_db_test # <--- REPLACE WITH YOUR LOCAL TEST DATABASE NAME
  username: postgres
  password: password # <--- REPLACE WITH YOUR LOCAL POSTGRES PASSWORD
  host: localhost
  port: 5432

production:
  # Define the PRIMARY database connection for production using DATABASE_URL
  # This uses the default settings and importantly, defines a reusable anchor
  primary: &primary_database_connection # <--- THIS LINE IS CRUCIAL FOR THE ANCHOR
    <<: *default # Inherit adapter, encoding, pool, timeout from default
    url: <%= ENV['DATABASE_URL'] %> # Heroku's database URL

  # NOW, define 'queue' and 'cache' as sub-sections of 'production'
  # And make them inherit all connection details from the 'primary_database_connection' anchor
  queue:
    <<: *primary_database_connection # <--- CORRECT INDENTATION & USAGE OF ANCHOR

  cache:
    <<: *primary_database_connection # <--- CORRECT INDENTATION & USAGE OF ANCHOR
    # You can add solid_cache specific options here if needed, e.g.:
    # options:
    #   max_size: <%= 256.megabytes %>
    #   namespace: <%= Rails.env %>